name: 'packet_man'
version: '1.0.0+1'
publish_to: none
environment: 
  sdk: '>=3.4.0 <4.0.0'
description: A Simple Opensource Post Man Alternative
dependencies: 
  cupertino_icons: '^1.0.6'
  drift: any
  drift_sqflite: any
  flutter: 
    sdk: flutter
  flutter_highlight: any
  font_awesome_flutter: any
  get_it: any
  http: any
  injectable: any
  path: any
  path_provider: any
  provider: any
  logger:
  lottie:
dev_dependencies: 
  build_runner: any
  drift_dev: any
  flutter_lints: '^3.0.0'
  flutter_test: 
    sdk: flutter
  import_sorter: any
  injectable_generator: any
  pubspec_dependency_sorter: any
  flutter_gen: 5.6.0
  flutter_gen_runner: 5.6.0
flutter: 
  uses-material-design: true
  assets:
    - assets/